// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piywbbjqrprkznpqbthd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpeXdiYmpxcnBya3pucHFidGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzgxMzYsImV4cCI6MjA1ODIxNDEzNn0.qPPIWi626NEyp4aslEQ-ZIEtPZwoCGyVmehYuamGhyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);